// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import HelloController from './hello_controller';
application.register('hello', HelloController);

import MenuController from './menu_controller';
application.register('menu', MenuController);

import ModalController from './modal_controller';
application.register('modal', ModalController);

import WebsocketProductController from './websocket_product_controller';
application.register('websocket-product', WebsocketProductController);

import { Alert } from 'tailwindcss-stimulus-components';
application.register('alert', Alert);
